[package]
name = "polaris-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
serde-duration-ext = "0.1.0"
schemars = "0.8.16"
serde_yaml = "0.9.34"
bytes = {version = "1.4.0"}
prost = {version = "0.12.4" }
prost-types = {version = "0.12.4" }
prost-build = {version = "0.12.4" }